name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          go build -tags prod -ldflags="-H=windowsgui -s -w -X main.version=${GITHUB_REF#refs/tags/}" -o "dist/memento_${GITHUB_REF#refs/tags/}.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: memento_${GITHUB_REF#refs/tags/}
          path: dist/memento_${GITHUB_REF#refs/tags/}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: false

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Creating release for tag: $TAG_NAME"

          # リリースの作成
          gh release create "$TAG_NAME" --title "$TAG_NAME"

          # 各ファイルをアップロード
          for asset in dist/*/* ; do
            gh release upload "$TAG_NAME" "$asset"
          done
